### ISSUE TITLE
Wrong rendering of etcd.service 

### ISSUE THREAD

**Issue by prep0sterous** [andrewrothstein/ansible-etcd-cluster#33]
Since https://github.com/andrewrothstein/ansible-etcd_cluster/pull/28 was rejected, I'll raise this as an issue.

etcd service template, using default configuration, renders as 

```ini
[Unit]
Description=Etcd Server
After=network.target

[Service]Type=notify
User=etcd
```

Needs proper whitespace control at https://github.com/andrewrothstein/ansible-etcd_cluster/blob/2184dea37ff568c5d7838a75196ecf6fe7ae0ac8/templates/etcd.service.j2#L6

**Comment by andrewrothstein** [comment]
I believe I remediated this in a flurry of commits. My apologies for pretending like I understood jinja2 whitespace handling without an interactive testing session. Hopefully this issue was squashed in the latest version (v3.0.7) I published to the galaxy.
Thanks for your attention to this role, Drew
